name: Build and Deploy Site

on:
  push:
    branches: [main, master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install packages
        run: |
          R -e 'install.packages(c("blogdown", "rmarkdown"))'
          
      - name: Build site
        run: |
          R -e 'blogdown::build_site()'
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public